version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python:
    image: python:3.10
    container_name: python_app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - mysql

volumes:
  mysql_data:
